name: tests

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        with:
          start: yarn demo
          command: yarn cypress
          wait-on: "http://localhost:3001"
